CREATE TYPE role as ENUM ('admin', 'basic');

CREATE TABLE IF NOT EXISTS users (
id TEXT UNIQUE PRIMARY KEY
username VARCHAR(40) UNIQUE NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(40) NOT NULL,
bio VARCHAR(1500),
user_role role
);